apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-app
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  replicas: 1
  selector:
    matchLabels:
      app: express-app
  template:
    metadata:
      labels:
        app: express-app
    spec:
      containers:
        - name: express-app
          image: collectiusacr.azurecr.io/express-app:961b12e7a4f2bc15c969a9dbfb2995c6b445853e
          imagePullPolicy: Always
          resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
          ports:
            - containerPort: 3000
