name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      GITHUB_TOKEN: ${{ secrets.PAT }}

    defaults:
      run:
        working-directory: . 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        if: github.event_name == 'push'
        run: |
          git config --local user.name actions-user
          git config --local user.email "actions@github.com"

          sed -i "s|image:.*|image: ${{ secrets.AZ_ACR_NAME }}.azurecr.io/express-app:${{ github.sha }}|g" ./manifests/deployment.yaml

          cat ./manifests/deployment.yaml

          git add manifests/deployment.yaml
          git commit -am "Updated deployment.yaml with latest build tag"
          git push

          az acr login --name ${{ secrets.AZ_ACR_NAME }}
            
          az acr build --image express-app:${{ github.sha }} --registry ${{ secrets.AZ_ACR_NAME }} .

          

