name: Build and Push Docker Image

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      GITHUB_TOKEN: ${{ secrets.PAT }}

    defaults:
      run:
        working-directory: . 

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Azure CLI
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build and Push Docker Image
        if: github.event_name == 'push'
        run: |
          echo "GITHUB_REF -> "$GITHUB_REF
          echo "GITHUB_HEAD_REF -> "$GITHUB_HEAD_REF
          echo "GITHUB_BASE_REF -> "$GITHUB_BASE_REF
          echo "GITHUB_REF_NAME -> "$GITHUB_REF_NAME

          echo "Hello, World!!!"

          az acr login --name ${{ secrets.AZ_ACR_NAME }}
          
          az acr build --image express-app:${{ github.sha }} --registry ${{ secrets.AZ_ACR_NAME }} .

          sed -i "s/{COMMIT_SHA}/${{ github.sha }}/g" ./manifests/deployment.yaml

          *Pushed by: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })

          cat ./manifests/deployment.yaml

          

